Query_voluntier_SQL

create or replace view DB_BL_SCM.CL_SCM.DVW_DT_VEHICLE_CO2_EMISSION_TARGETS(
	DT_INGESTION_TIMESTAMP,
	CD_MARKETS_CLUSTER_CODE,
	CD_HOMOLOGATION_CODE,
	GN_ENERGY_BASED_TARGET_TYPE,
	GN_YEAR_NUMBER,
	GN_MONTH_NUMBER,
	GN_MARKETS_GROUP_NAME,
	CD_MARKET_ISO_CODE,
	GN_BRAND_NAME,
	GN_AGGREGATION_LEVEL_NAME,
	NM_CO2_EMISSION_TARGET_NUMBER,
	NM_SALES_VOLUME_TARGET_PERCENTAGE_NUMBER
) as (
    select
        DT_INGESTION_TIMESTAMP,
        CD_MARKETS_CLUSTER_CODE,
        CD_HOMOLOGATION_CODE,
        GN_ENERGY_BASED_TARGET_TYPE,
        GN_YEAR_NUMBER,
        GN_MONTH_NUMBER,
        GN_MARKETS_GROUP_NAME,
        CD_MARKET_ISO_CODE,
        GN_BRAND_NAME,
        GN_AGGREGATION_LEVEL_NAME,
        NM_CO2_EMISSION_TARGET_NUMBER,
        NM_SALES_VOLUME_TARGET_PERCENTAGE_NUMBER
    from DB_BL_SCM.BL_SCM.DT_VEHICLE_CO2_EMISSION_TARGETS
    where lower(GN_ENERGY_BASED_TARGET_TYPE) IN (
        'co2tot',
        'bevmixtarget',
        'phevmixtarget'
    )
);